---------------------------------------
Begin Slurm Prolog: Oct-05-2024 10:52:15
Job ID:    1556161
User ID:   azhou60
Account:   gts-bzhao94
Job name:  neuralcbcptest_test5_train20
Partition: cpu-small
QOS:       inferno
---------------------------------------

CondaError: Run 'conda init' before 'conda deactivate'

2024-10-05 10:53:52.111564: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/slurm/current/lib:/usr/local/pace-apps/spack/packages/linux-rhel9-x86_64_v3/gcc-12.3.0/mvapich2-2.3.7-1-qv3gjagtbx5e3rlbdy6iy2sfczryftyt/lib:/opt/slurm/current/lib:/opt/pmix/4.2.6/lib:/usr/local/pace-apps/spack/packages/linux-rhel9-x86_64_v3/gcc-12.3.0/libxml2-2.10.3-ve5kggawwlt6jijzmrfy7idkx5hcwmuw/lib:/usr/local/pace-apps/spack/packages/linux-rhel9-x86_64_v3/gcc-12.3.0/xz-5.4.1-23t2osmoz6du7oygrv5zeiignuxhmmp4/lib:/usr/local/pace-apps/spack/packages/linux-rhel9-x86_64_v3/gcc-12.3.0/libiconv-1.17-fsjufoyqbs3t36il6apgxqcqrceerbe2/lib:/usr/local/pace-apps/spack/packages/linux-rhel9-x86_64_v3/gcc-12.3.0/libpciaccess-0.17-pjfe4ct4gfm5k26s36hmewhbz4k232dl/lib:/usr/local/pace-apps/spack/packages/linux-rhel9-x86_64_v3/gcc-11.3.1/gcc-12.3.0-ukkkutsxfl5kpnnaxflpkq2jtliwthfz/lib64:/usr/local/pace-apps/spack/packages/linux-rhel9-x86_64_v3/gcc-11.3.1/gcc-12.3.0-ukkkutsxfl5kpnnaxflpkq2jtliwthfz/lib:/usr/local/pace-apps/spack/packages/linux-rhel9-x86_64_v3/gcc-12.3.0/zlib-1.2.13-3qhjpij2pji47kfanmlflvwk5ljcn5lh/lib:/usr/local/pace-apps/spack/packages/linux-rhel9-x86_64_v3/gcc-12.3.0/mpc-1.3.1-3zvixith5i243hwiill4exyu3lf2q6ad/lib:/usr/local/pace-apps/spack/packages/linux-rhel9-x86_64_v3/gcc-12.3.0/mpfr-4.2.0-tox4bdsc25zr763rnq5gzlukfbvw7uj7/lib:/usr/local/pace-apps/spack/packages/linux-rhel9-x86_64_v3/gcc-12.3.0/gmp-6.2.1-n7dzsse5e3f6w5z6q6cuqursydg6yypo/lib::
Traceback (most recent call last):
  File "/storage/home/hcoda1/6/azhou60/NeuralLCB_C/realworld_main.py", line 18, in <module>
    from algorithms.neural_offline_bandit_cp import ApproxNeuraLCB_cp
  File "/storage/home/hcoda1/6/azhou60/NeuralLCB_C/algorithms/neural_offline_bandit_cp.py", line 12, in <module>
    from tensorflow.keras.models import Sequential, clone_model
  File "/storage/home/hcoda1/6/azhou60/.conda/envs/jax_tf28/lib/python3.9/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/storage/home/hcoda1/6/azhou60/.conda/envs/jax_tf28/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/storage/home/hcoda1/6/azhou60/.conda/envs/jax_tf28/lib/python3.9/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/storage/home/hcoda1/6/azhou60/.conda/envs/jax_tf28/lib/python3.9/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/storage/home/hcoda1/6/azhou60/.conda/envs/jax_tf28/lib/python3.9/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/storage/home/hcoda1/6/azhou60/.conda/envs/jax_tf28/lib/python3.9/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/storage/home/hcoda1/6/azhou60/.conda/envs/jax_tf28/lib/python3.9/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/storage/home/hcoda1/6/azhou60/.conda/envs/jax_tf28/lib/python3.9/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/storage/home/hcoda1/6/azhou60/.conda/envs/jax_tf28/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 621, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
---------------------------------------
Begin Slurm Epilog: Oct-05-2024 10:54:01
Job ID:        1556161
Array Job ID:  _4294967294
User ID:       azhou60
Account:       gts-bzhao94
Job name:      neuralcbcptest_test5_train20
Resources:     cpu=1,mem=2G,node=1
Rsrc Used:     cput=00:01:46,vmem=0,walltime=00:01:46,mem=313912K,energy_used=0
Partition:     cpu-small
QOS:           inferno
Nodes:         atl1-1-02-003-16-1
---------------------------------------
